name = "marginalia-sync"
main = "src/index.js"
compatibility_date = "2026-04-01"
workers_dev = true

[[durable_objects.bindings]]
name = "MARGINALIA_LIBRARY"
class_name = "LibraryRoom"

[[migrations]]
tag = "v1"
new_sqlite_classes = [ "LibraryRoom" ]

[vars]
ALLOWED_ORIGINS = "http://localhost:8010,http://127.0.0.1:8010,https://emh.github.io,https://emh.io"
